name: Minecraft Server (Educational)

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  minecraft:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # Max 6 hours (GitHub limit)

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'  # Minecraft 1.21.8+ requires Java 21

      - name: Install rclone (Google Drive sync)
        run: sudo apt-get update -qq && sudo apt-get install -y rclone

      - name: Configure Google Drive
        env:
          RCLONE_CONFIG: |
            [gdrive]
            type = drive
            scope = drive
            service_account_file = /tmp/credentials.json
          RCLONE_CREDENTIALS: ${{ secrets.GDRIVE_CREDENTIALS }}  # Base64-encoded
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
          echo "$RCLONE_CREDENTIALS" | base64 --decode > /tmp/credentials.json

      - name: Download Server & World
        run: |
          # Download PaperMC 1.21.8 (latest stable)
          wget https://api.papermc.io/v2/projects/paper/versions/1.21.8/builds/31/downloads/paper-1.21.8-31.jar -O server.jar
          # Sync world from Google Drive (skip if first run)
          rclone copy -P gdrive:/minecraft/world ./world/ || echo "No existing world found (first run)."

      - name: Start Minecraft Server
        run: |
          # Accept EULA automatically
          echo "eula=true" > eula.txt
          # Start server with auto-restart (max 5h 50m to allow clean shutdown)
          while [ $SECONDS -lt 21000 ]; do
            java -Xmx6G -Xms2G -jar server.jar nogui
            echo "Server stopped/crashed. Restarting in 5 seconds..."
            sleep 5
          done

      - name: Backup World to Google Drive
        if: always()  # Upload even if job fails
        run: |
          rclone copy -P ./world/ gdrive:/minecraft/world/ --drive-chunk-size 64M
